# Let Nixpacks auto-detect Python from requirements.txt
# It will automatically create venv and install dependencies

[phases.setup]
nixPkgs = ["python312", "nodejs"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install -g @lighthouse-web3/sdk",
  "lighthouse-web3 api-key --import $LIGHTHOUSE_API_KEY || true"
]

[start]
cmd = "cd apps/worker && python run.py"
