[phases.setup]
nixPkgs = ["python310Full"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "cd apps/worker && python run.py"
