# Railway deployment configuration for Python worker with Lighthouse SDK
# Extends auto-detected Python provider with Node.js for Lighthouse CLI

[phases.setup]
nixPkgs = ["...", "nodejs"]

[phases.install]
cmds = [
  "...",
  "npm install -g @lighthouse-web3/sdk",
  "lighthouse-web3 --version || echo 'Lighthouse CLI not found in PATH'",
  "lighthouse-web3 api-key --import $LIGHTHOUSE_API_KEY || echo 'API key import skipped'"
]

[start]
cmd = "/opt/venv/bin/python apps/worker/run.py"

