# Extend Nixpacks auto-detection with Node.js for Lighthouse CLI
# The "..." syntax extends the default provider behavior

[phases.setup]
nixPkgs = ["...", "nodejs"]

[phases.install]
cmds = [
  "...",
  "npm install -g @lighthouse-web3/sdk",
  "export PATH=\"/root/.nix-profile/bin:$PATH\" && lighthouse-web3 --version",
  "export PATH=\"/root/.nix-profile/bin:$PATH\" && lighthouse-web3 api-key --import $LIGHTHOUSE_API_KEY || true"
]

[start]
cmd = "export PATH=\"/root/.nix-profile/bin:$PATH\" && cd apps/worker && python run.py"
