# Extend Nixpacks auto-detection with Node.js for Lighthouse CLI
# The "..." syntax extends the default provider behavior

[phases.setup]
nixPkgs = ["...", "nodejs"]

[phases.install]
cmds = [
  "...",
  "npm install -g @lighthouse-web3/sdk",
  "npm root -g",
  "npm bin -g",
  "which node",
  "find /root -name lighthouse-web3 2>/dev/null || true",
  "ls -la $(npm bin -g) || true"
]

[start]
cmd = "export PATH=\"$(npm bin -g):$PATH\" && cd apps/worker && python run.py"
