# Extend Nixpacks auto-detection with Node.js for Lighthouse CLI
# The "..." syntax extends the default provider behavior

[phases.setup]
nixPkgs = ["...", "nodejs"]

[phases.install]
cmds = [
  "...",
  "npm install -g @lighthouse-web3/sdk",
  "ls -la /nix/store/*/bin/lighthouse-web3 || true",
  "PATH=\"/nix/store/jz54v1m0ldqivx5i45q8i05pz5clf842-nodejs-20.18.0/bin:$PATH\" lighthouse-web3 --version || true",
  "PATH=\"/nix/store/jz54v1m0ldqivx5i45q8i05pz5clf842-nodejs-20.18.0/bin:$PATH\" lighthouse-web3 api-key --import $LIGHTHOUSE_API_KEY || true"
]

[variables]
PATH = "/nix/store/jz54v1m0ldqivx5i45q8i05pz5clf842-nodejs-20.18.0/bin:$PATH"

[start]
cmd = "export PATH=\"/nix/store/jz54v1m0ldqivx5i45q8i05pz5clf842-nodejs-20.18.0/bin:$PATH\" && cd apps/worker && python run.py"
