# Railway deployment configuration for Python worker with Lighthouse SDK
# Extends auto-detected Python provider with Node.js for Lighthouse native encryption

[phases.setup]
nixPkgs = ["...", "nodejs"]

[phases.install]
cmds = [
  "...",
  "npm install --prefix apps/worker",
  "echo 'Lighthouse SDK installed in apps/worker/node_modules/'"
]

[start]
cmd = "python apps/worker/run.py"

